### ISSUE TITLE
Xively API key too big for library

### ISSUE THREAD

**Issue by Scott216** [davidegironi/spark-xivelylib#1]
I'm trying to use your library with my Spark core.  This is my first Spark project, but I've used Xively a lot with Arduinos.  My Xively API key is 64 characters long, but you've only allocated 48 characters:
See:
https://github.com/davidegironi/spark-xivelylib/blob/master/firmware/XivelyLib.h#L17

Can you update your library in Particle.io to accept longer API keys?

Thanks

**Comment by Scott216** [comment]
I just generated a new key for my feed and I see it's only 48 characters, so I'll just use that one.   Maybe it's just the master key that's 64 characters.  I think the key that was assigned to me I got from Cosm, maybe even when it was Pachube.

**Comment by davidegironi** [comment]
Well done. Indeed xively "API Keys" for feeds are 48 characters as far as i know.
Thank you for feedback.
